// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebDevLab2.Model.Context;

#nullable disable

namespace WebDevLab2.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20240313111749_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebDevLab2.Model.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Developer");
                });

            modelBuilder.Entity("WebDevLab2.Model.DeveloperCommentary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentary")
                        .HasColumnType("text");

                    b.Property<int>("CommunityInteraction")
                        .HasColumnType("integer");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("integer");

                    b.Property<int>("GameQuality")
                        .HasColumnType("integer");

                    b.Property<int>("Monetisation")
                        .HasColumnType("integer");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<bool>("Recommend")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("OwnerId");

                    b.ToTable("DeveloperCommentary");
                });

            modelBuilder.Entity("WebDevLab2.Model.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmmountOfPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<int>("Mark")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("WebDevLab2.Model.GameCommentary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AudioQuality")
                        .HasColumnType("integer");

                    b.Property<int>("Bugs")
                        .HasColumnType("integer");

                    b.Property<string>("Commentary")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("Gameplay")
                        .HasColumnType("integer");

                    b.Property<int>("Graphics")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("Plot")
                        .HasColumnType("integer");

                    b.Property<bool>("Recommend")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OwnerId");

                    b.ToTable("GameCommentary");
                });

            modelBuilder.Entity("WebDevLab2.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("WebDevLab2.Model.DeveloperCommentary", b =>
                {
                    b.HasOne("WebDevLab2.Model.Developer", "Developer")
                        .WithMany("DeveloperCommentaries")
                        .HasForeignKey("DeveloperId");

                    b.HasOne("WebDevLab2.Model.Player", "Owner")
                        .WithMany("DeveloperComments")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Developer");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WebDevLab2.Model.Game", b =>
                {
                    b.HasOne("WebDevLab2.Model.Developer", "Developer")
                        .WithMany("CreatedGames")
                        .HasForeignKey("DeveloperId");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("WebDevLab2.Model.GameCommentary", b =>
                {
                    b.HasOne("WebDevLab2.Model.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDevLab2.Model.Player", "Owner")
                        .WithMany("GameComments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WebDevLab2.Model.Developer", b =>
                {
                    b.Navigation("CreatedGames");

                    b.Navigation("DeveloperCommentaries");
                });

            modelBuilder.Entity("WebDevLab2.Model.Game", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("WebDevLab2.Model.Player", b =>
                {
                    b.Navigation("DeveloperComments");

                    b.Navigation("GameComments");
                });
#pragma warning restore 612, 618
        }
    }
}
